apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helmtest
  namespace: kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helmtest
  template:
    metadata:
      labels:
        app: helmtest
    spec:
      containers:
        - image: 'docker.io/opsmx11/restapp:simple-1.0'
          imagePullPolicy: Always
          name: restapp
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9092
              name: prometheus
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: helmtest-service
  namespace: kube
spec:
  ports:
    - name: canary
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: reports
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: helmtest
  type: NodePort
